steps:
  # This step uses the standard Docker builder to build the image.
  # The '-t' flag tags the image with the specified name.
  # The '.' at the end specifies that the build context is the current directory.
  # We use a private copy from our regional Artifact Registry to comply with location policies.
  - name: 'europe-west4-docker.pkg.dev/cf-mccuagcf-recommenders-ht/metro-recs-repo/docker-builder'
    args:
      - 'build'
      - '-t'
      - 'europe-west4-docker.pkg.dev/cf-mccuagcf-recommenders-ht/metro-recs-repo/metro-recs-pipeline:latest-gpu'
      - '.'

# This section tells Cloud Build to push the successfully built image to Artifact Registry.
images:
  - 'europe-west4-docker.pkg.dev/cf-mccuagcf-recommenders-ht/metro-recs-repo/metro-recs-pipeline:latest-gpu'

# This section sets build-wide options.
options:
  # Specify a regional GCS bucket for staging source to comply with location policies.
  gcs_source_staging_dir: 'gs://recs_metroua_cloudbuild/source'